base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),

]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('-/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<str:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<str:slug>/-/issue/', views.CreateIssueView.as_view(), name='create_issue'),
    path('<str:slug>/-/issue/<str:issue_slug>/', views.IssueView.as_view(), name='issue_detail'),
    path('<str:slug>/add-collaborators/', views.AddRemoveCollaboratorView.as_view(), name='add_remove_collaborator'),
    path('-/assign/', views.assign_task, name='assign_task'),
    path('<str:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<str:slug>/edit/', views.ProjectEditView.as_view(), name='project_edit'),
    path('<str:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
]

base/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from bugtail.helpers.project_helper import get_user_projects
# Create your views here.

class DashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        projects = get_user_projects(self.request.user)[:8]
        context = {
            'projects':projects,
            'view_all': True if projects.count() > 8 else False
        }
        return render(request, 'index.html', context)

def error_404(request, exception):
    return render(request, '404.html')

def error_500(request, *args, **kwargs):
    return render(request, '500.html')

base/templates/base.html
{% extends 'partials/_layout.html' %}
{% block content %}
<div class="wrapper">
    {% include 'partials/_sidebar.html' %}
    <div class="main">
        {% include 'partials/_navbar.html' %}
        <main class="content">
            <div class="container-fluid">

                <div class="header">
                    <h1 class="header-title">
                        {% block page_header_title %}Blank Page{% endblock page_header_title %}
                    </h1>
                    <p class="header-subtitle">
                        <div class="d-flex text-white justify-content-between">
                            <div>
                                {% block page_header_subtitle %}
                                    Your bounce rate increased by 5.25% over the past 30 days.
                                {% endblock page_header_subtitle %}
                            </div>
                            
                            <div>
                                {% block contributor %}
                                    
                                {% endblock %}
                            </div>
                            
                        </div>
                    </p>
                </div>
                
                <div class="row">

                    <div class="col-12">
                        {% block page_content %}
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title mb-0">Empty card</h5>
                            </div>
                            <div class="card-body">
                                <div class="my-5">&nbsp;</div>
                            </div>
                        </div>
                        {% endblock page_content %}
                    </div>

                </div>
                
            </div>
        </main>
        {% include 'partials/_footer.html' %}
    </div>

</div>
{% endblock content %}

base/templates/index.html
{% extends 'base.html' %}
{% block page_header_title %}Projects Overview{% endblock page_header_title %}
{% block page_header_subtitle %}
    Your bounce rate increased by 5.25% over the past 30 days.
{% endblock page_header_subtitle %}
{% block contributor %}
<a href="{% url 'projects:project_create' %}" class="text-white btn btn-primary" title="Create a Project">
    <i class="fas fa-project-diagram"></i>
</a>                               
{% endblock contributor %}
{% block page_content %}
<div class="row">
	{% if projects %}
	{% for project in projects %}
	<div class="col-sm-3">
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col mt-0">
						<h5 class="card-title">{% if project.author == request.user %}Owner{% else %}Collaborator{% endif %}</h5>
					</div>

					<div class="col-auto">
						<div class="avatar">
							<div class="avatar-title rounded-circle bg-primary-dark">
								<i class="align-middle" 
								data-feather="{% if project.author == request.user %}user{% else %}users{% endif %}"></i>
							</div>
						</div>
					</div>
				</div>
				<h1 class="display-5 mt-2 mb-4">{{project.name}}</h1>
				<div class="mb-0">
					{{project.desc | truncatewords:3}}
				</div>
				<a href="{% url 'projects:project_detail' project.slug %}">View</a>
				
			</div>
		</div>
	</div>
	{% endfor %}
	{% if view_all %}
	<div>
		<a href="{% url 'projects:project_list' %}" class="btn btn-primary">View</a>
	</div>
	{% endif %}
	{% else %}
	<div class="col-12">
		<div class="card p-3">
			<p>You have not Project Yet! <span class="fw-bold">Start a Project <a href="{% url 'projects:project_create' %}">Here</a></span></p>
		</div>
	</div>
	{% endif %}
</div>




{% endblock page_content %}
{% block custom_scripts %}
<script>
	document.addEventListener("DOMContentLoaded", function () {
		var map = new jsVectorMap({
			map: "world",
			selector: "#world_map",
			zoomButtons: true,
			selectedRegions: [
				'US',
				'SA',
				'DE',
				'FR',
				'CN',
				'AU',
				'BR',
				'IN',
				'GB'
			],
			regionStyle: {
				initial: {
					fill: '#e4e4e4',
					"fill-opacity": 0.9,
					stroke: 'none',
					"stroke-width": 0,
					"stroke-opacity": 0
				},
				selected: {
					fill: window.theme.primary,
				}
			},
			zoomOnScroll: false
		});
		window.addEventListener("resize", () => {
			map.updateSize();
		});
		setTimeout(function () {
			map.updateSize();
		}, 250);
	});
</script>
<script>
	document.addEventListener("DOMContentLoaded", function () {
		// Pie chart
		new Chart(document.getElementById("chartjs-dashboard-pie"), {
			type: 'pie',
			data: {
				labels: ["Chrome", "Firefox", "IE", "Other"],
				datasets: [{
					data: [4401, 4003, 1589],
					backgroundColor: [
						window.theme.primary,
						window.theme.warning,
						window.theme.danger,
						"#E8EAED"
					],
					borderColor: "transparent"
				}]
			},
			options: {
				responsive: !window.MSInputMethodContext,
				maintainAspectRatio: false,
				legend: {
					display: false
				},
				cutoutPercentage: 75
			}
		});
	});
</script>
<script>
	document.addEventListener("DOMContentLoaded", function () {
		// Radar chart
		new Chart(document.getElementById("chartjs-dashboard-radar"), {
			type: "radar",
			data: {
				labels: ["Technology", "Sports", "Media", "Gaming", "Arts"],
				datasets: [{
					label: "Interests",
					backgroundColor: "rgba(0, 123, 255, 0.2)",
					borderColor: "#2979ff",
					pointBackgroundColor: "#2979ff",
					pointBorderColor: "#fff",
					pointHoverBackgroundColor: "#fff",
					pointHoverBorderColor: "#2979ff",
					data: [70, 53, 82, 60, 33]
				}]
			},
			options: {
				maintainAspectRatio: false,
				legend: {
					display: false
				}
			}
		});
	});
</script>
<script>
	document.addEventListener("DOMContentLoaded", function () {
		// Bar chart
		new Chart(document.getElementById("chartjs-dashboard-bar-alt"), {
			type: "bar",
			data: {
				labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
				datasets: [{
					label: "Last year",
					backgroundColor: window.theme.primary,
					borderColor: window.theme.primary,
					hoverBackgroundColor: window.theme.primary,
					hoverBorderColor: window.theme.primary,
					data: [54, 67, 41, 55, 62, 45, 55, 73, 60, 76, 48, 79],
					barPercentage: .75,
					categoryPercentage: .5
				}, {
					label: "This year",
					backgroundColor: "#E8EAED",
					borderColor: "#E8EAED",
					hoverBackgroundColor: "#E8EAED",
					hoverBorderColor: "#E8EAED",
					data: [69, 66, 24, 48, 52, 51, 44, 53, 62, 79, 51, 68],
					barPercentage: .75,
					categoryPercentage: .5
				}]
			},
			options: {
				maintainAspectRatio: false,
				legend: {
					display: false
				},
				scales: {
					yAxes: [{
						gridLines: {
							display: false
						},
						stacked: false,
						ticks: {
							stepSize: 20
						}
					}],
					xAxes: [{
						stacked: false,
						gridLines: {
							color: "transparent"
						}
					}]
				}
			}
		});
	});
</script>
<script>
	document.addEventListener("DOMContentLoaded", function () {
		$("#datatables-dashboard-traffic").DataTable({
			pageLength: 7,
			lengthChange: false,
			bFilter: false,
			autoWidth: false,
			order: [
				[1, "desc"]
			]
		});
	});
</script>
{% endblock custom_scripts %}