accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'

urlpatterns = [
    path('edit-account/', views.ChangeUserDetailsView.as_view(), name='edit_account'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
]

base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),

]

notifications/urls.py
from django.urls import path
from notifications import views

app_name = 'notifications'

urlpatterns = [
    path('mark-all-as-read/', views.MarkNotifications.as_view(), name='mark_all_as_read'),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('-/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<str:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<str:slug>/-/issue/', views.CreateIssueView.as_view(), name='create_issue'),
    path('<str:slug>/-/issue/<str:issue_slug>/', views.IssueView.as_view(), name='issue_detail'),
    path('<str:slug>/add-collaborators/', views.AddRemoveCollaboratorView.as_view(), name='add_remove_collaborator'),
    path('-/assign/', views.assign_task, name='assign_task'),
    path('<str:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<str:slug>/edit/', views.ProjectEditView.as_view(), name='project_edit'),
    path('<str:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
]

projects/models.py
from accounts.models import User
from django.db import models
from bugtail.helpers import model_helper

# Create your models here.

class Project(model_helper.AuthorDescNameTimeBasedModel):
    slug = models.SlugField(default=model_helper.gen_slug)
    collaborators = models.ManyToManyField(User, related_name='collaborators', blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.name} {self.slug} project'
    
    def get_author(self):
        return self.author
    
    def get_collaborators(self):
        collaborators = [self.get_author()]
        return collaborators + list(self.collaborators.all())
    


class IssueLabel(model_helper.TimeBasedModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=10)
    short_name = models.CharField(max_length=5)

    class Meta:
        verbose_name = 'Issue Label'
        verbose_name_plural = 'Issue Labels'

    def __str__(self):
        return f'{self.project.name} - {self.name}'





class Issue(model_helper.NameDescTimeBasedModel):
    class IssuePriorityChoices(models.TextChoices):
        low = 'Low', 'Low'
        high = 'High', 'High'
        moderate = 'Moderate', 'Moderate'
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    slug = models.SlugField(default=model_helper.gen_slug)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, 
        blank=True, related_name='issue_assignee')
    priority = models.CharField(max_length=100, choices=IssuePriorityChoices.choices,
    default=IssuePriorityChoices.moderate)
    label = models.ForeignKey(IssueLabel, on_delete=models.SET_NULL, null=True, blank=True,
    related_name='issue_label')


    class Meta:
        verbose_name = 'Issue'
        verbose_name_plural = 'Issues'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.project.slug} task {self.slug} - {self.created_at.date()}' 

    def assginee_image(self):
        return self.assigned_to.profile.image_url()

    

base/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from bugtail.helpers.project_helper import get_user_projects
# Create your views here.

class DashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        projects = get_user_projects(self.request.user)[:8]
        context = {
            'projects':projects,
            'view_all': True if projects.count() > 8 else False
        }
        return render(request, 'index.html', context)

def error_404(request, exception):
    return render(request, '404.html')

def error_500(request, *args, **kwargs):
    return render(request, '500.html')

base/templates/partials/_add_collaborator_modal.html
<div class="modal fade" id="addCollaboratorModal" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Collaborators</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body m-3 text-dark">
                <p class="mb-0">
                    Enter the correct email address of the person collaborating with you on <b>{{project.name}}</b>
                </p>
                <div class="d-flex my-2">
                    <input type="email" name="" class="form-control" id="addCollaboratorField">
                    <div class="mx-2">
                        <button type="submit" class="btn btn-primary" id="addCollaboratorBtn" onclick="addCollaborator()">
                            <i class="fas fa-plus"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

base/templates/partials/_alert_notification.html
<script>
    const showNotification = (message, messageType) => {
        toastr[messageType](message, {
            positionClass: 'toast-top-center',
            closeButton: true,
            progressBar: true,
            newestOnTop: true,
            rtl: true,
            timeOut: '5000'
        });
    }
</script>

base/templates/partials/_collaborators_modal.html
<div class="modal fade" id="collaboratorsModal" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fas fa-user-friends"></i> Collaborators</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body m-3 text-dark">
                {% if collaborators %}
                {% for collaborator in collaborators %}
                <div class="d-flex my-2 justify-content-between " id="user-{{collaborator.email}}">
                    <div class="d-flex">
                        <img src="{{collaborator.profile.image_url}}"
                         alt="" width="40px" height="40px" class="rounded-circle">
                        <p class="fs-4 pt-1 mx-3">
                            {{collaborator.username.title}}
                        </p>
                    </div>
                    <div class="mx-2">
                        <button type="submit" class="btn btn-primary" data-email="{{collaborator.email}}" id="addCollaboratorBtn" onclick="removeCollaborator(this)">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <p class="text-center">No Collaborator Yet!</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

base/templates/partials/_footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-8 text-start">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Support</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Terms of Service</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <div class="col-4 text-end">
                <p class="mb-0">
                    &copy; 2021 - <a href="dashboard-default.html" class="text-muted">Spark</a>
                </p>
            </div>
        </div>
    </div>
</footer>

base/templates/partials/_issue_modal.html
<div class="modal fade" id="centeredIssueModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <form  method="post" class="issueForm">
            <div class="modal-header">
                <h5 class="modal-title">Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body m-3">
                
                    <div>
                        <label for="">Title</label>
                        <input type="text" id="issueTitle" name="title" class="form-control">
                    </div>
                    <div>
                        <label for="">Description</label>
                        <textarea name="desc" id="issueDesc" cols="30" rows="5" class="form-control"></textarea>
                    </div>
                    
                    <div>
                        {{project.issueprioritychoices}}
                        <label for="">Priority</label>
                        {{form.priority}}
                    </div>
                    <div>
                        <div class="row">
                            <div class="col">
                                <label for="">Label</label>
                                <select name="label" id="issueLabel" class="form-select">
                                    {% for label in project.issuelabel_set.all %}
                                    <option value="{{label.short_name}}" style="color: {{label.color}};">
                                        {{label.name.title}}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                            {% if project.collaborators.all %}
                            <div class="col">
                                <label for="">Assigned to</label>
                                <select name="assignee" id="" class="form-select">
                                    {% for collaborator in project.collaborators.all %}
                                    <option value="">{{collaborator.email}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            {% endif %}
                        </div>
                    </div>   
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
        
        </div>
    </div>
</div>

base/templates/partials/_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">
	<title>Bugtail</title>
    {% include 'partials/_stylesheet.html' %}
	<script src="{% static 'js/settings.js' %}"></script>
    {% block custom_styles %}

    {% endblock custom_styles %}
	<!-- END SETTINGS -->
</head>

<body>
    <div class="splash active">
		<div class="splash-icon"></div>
	</div>
    {% block content %}

    {% endblock content %}
    {% include 'partials/_script.html' %}
	{% include 'partials/_alert_notification.html' %}
    {% block custom_scripts %}

    {% endblock custom_scripts %}

</body>

</html>

base/templates/partials/_navbar.html
{% load notification_extra %}
<nav class="navbar navbar-expand navbar-theme">
    <a class="sidebar-toggle d-flex me-2">
        <i class="hamburger align-self-center"></i>
    </a>

    <form class="d-none d-sm-inline-block">
        <input class="form-control form-control-lite" type="text" placeholder="Search projects...">
    </form>

    <div class="navbar-collapse collapse">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown ms-lg-2">
                {% unread_notifications user as notifications %}
                <a class="nav-link dropdown-toggle position-relative" href="#" id="alertsDropdown"
                    data-bs-toggle="dropdown">
                    <i class="align-middle fas fa-bell"></i>
                    {% if notifications %}
                    <span class="indicator"></span>
                    {% endif %}
                </a>
                
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="alertsDropdown">
                    {% if notifications %}
                    <div class="dropdown-menu-header">
                        {{notifications.count}} New Notifications
                    </div>
                    <div class="list-group">
                        {% for notification in notifications %}
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="ms-1 text-danger fas fa-fw fa-bell"></i>
                                </div>
                                <div class="col-10">    
                                    <div class="text-muted small mt-1">{{notification.desc | truncatewords:15}}
                                    </div>
                                    <div class="text-muted small mt-1">{{notification.created_at | timesince}} ago</div>
                                </div>
                            </div>
                        </a>
                        {% endfor %}

                    </div>
                    <div class="dropdown-menu-footer">
                        <a href="#" class="text-muted" onclick="markRead()">Mark all as Read</a>
                    </div>
                    {% else %}
                    <div class="dropdown-menu-footer">
                        <a href="#" class="text-muted">No new notifications</a>
                    </div>
                    {% endif %}
                    
                </div>
            </li>
            <li class="nav-item dropdown ms-lg-2">
                <a class="nav-link dropdown-toggle position-relative" href="#" id="userDropdown"
                    data-bs-toggle="dropdown">
                    <i class="align-middle fas fa-cog"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:settings' %}"><i class="align-middle me-1 fas fa-fw fa-cogs"></i>
                        Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}"><i
                            class="align-middle me-1 fas fa-fw fa-arrow-alt-circle-right"></i> Sign out</a>
                </div>
            </li>
        </ul>
    </div>

</nav>
<script>
    const markRead = () => {
        $.ajax({
            url : `{% url 'notifications:mark_all_as_read' %}`,
            method : 'GET',
            success : res => {
                $('.list-group').empty()
                $('.dropdown-menu-header').css('display', 'none')
                $('.indicator').css('display', 'none')
                $('.dropdown-menu-footer').empty()
                $('.dropdown-menu-footer').append(
                    `<a href="#" class="text-muted">No new notifications</a>`
                )
                showNotification(res['message'], res['messageType'])
            },
            error : err => {
                showNotification('Error getting Notifications', 'error')
            }
        })
        
        console.log('Read')
    }
</script>

base/templates/partials/_right_offset_canva.html
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">Assign Task</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div id="offcanvas-desc">

        </div>
        <select name="" id="assign-select" class="form-select " onchange="assignTask(this)">
            <option value="">None</option>
            {% for collaborator in project.get_collaborators %}
            {% if collaborator == request.user %}
            <option value="{{request.user.email}}">Assign to Me</option>
            {% else %}
            <option value="{{collaborator.email}}">{{collaborator}}</option>
            {% endif %}
            {% endfor %}
        </select>
    </div>
</div>

base/templates/partials/_script.html
{% load static %}

<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/dropzone.min.js' %}"></script>

base/templates/partials/_sidebar.html
{% load static %}
{% load project_extras %}
<nav id="sidebar" class="sidebar">
    <a class="sidebar-brand" href="{% url 'base:dashboard' %}">
        <svg>
            <use xlink:href="#ion-ios-pulse-strong"></use>
        </svg>
        Bugtail
    </a>
    <div class="sidebar-content">
        <div class="sidebar-user">
            <img src="{{user.profile.image_url}}" class="img-fluid rounded-circle mb-2" alt="Linda Miller" />
            <div class="fw-bold">{{user.username}}</div>
            <small>{{user.profile.bio | truncatewords:6}}</small>
        </div>

        <ul class="sidebar-nav">
            <li class="sidebar-header">
                Main
            </li>
            <li class="sidebar-item">
                <a class="sidebar-link" href="{% url 'base:dashboard' %}">
                    <i class="align-middle me-2 fas fa-fw fa-home"></i> <span class="align-middle">Dashboard</span>
                </a>
            </li>
            <li class="sidebar-item active">
                <a data-bs-target="#pages" data-bs-toggle="collapse" class="sidebar-link">
                    <i class="align-middle me-2 fas fa-fw fa-project-diagram"></i> <span class="align-middle">Projects</span>
                </a>
                <ul id="pages" class="sidebar-dropdown list-unstyled collapse show" data-bs-parent="#sidebar">

                    <li class="sidebar-item"><a class="sidebar-link" href="{% url 'projects:project_list' %}">All Projects</a></li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a class="sidebar-link" href="{% url 'accounts:settings' %}">
                    <i class="align-middle me-2 fa-fw fas fa-cog"></i> <span class="align-middle">Settings</span>
                </a>
                
            </li>
        </ul>
    </div>
</nav>

base/templates/partials/_stylesheet.html
{% load static %}
<!-- PICK ONE OF THE STYLES BELOW -->
{% comment %}
<link href="{% static 'css/modern.css' %}" rel="stylesheet">
{% endcomment %}
{% comment %}
<link href="{% static 'css/classic.css' %}" rel="stylesheet">
{% endcomment %}
<link href="{% static 'css/dark.css' %}" rel="stylesheet">
<link href="{% static 'css/dropzone.min.css' %}" rel="stylesheet">
{% comment %}
<link href="{% static 'css/light.css' %}" rel="stylesheet">
{% endcomment %}

<style>
    body {
        opacity: 0;
    }
    .form-show{
        display: none;
    }
</style>

base/templates/partials/_task_card.html
<div class="card mb-3 bg-light cursor-grab" data-slug="{{issue.slug}}">
    <div class="card-body p-3">
        <p>
            {{issue.name}}
        </p>
        
        <div class="float-end mt-n1">
            {% if issue.assigned_to %}
            <img src="{{issue.assginee_image}}" width="32" height="32" class="rounded-circle" alt="Avatar"
            data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" onclick="getTask(this)" 
            data-title="{{issue.name}}" data-desc="{{issue.desc}}" data-slug="{{issue.slug}}" data-assigned-to="{{issue.assigned_to.email}}">
            {% else %}
            <div class="pt-2">
                <a href="" class="text-decoration-none text-dark" data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" onclick="getTask(this)" 
            data-title="{{issue.name}}" data-desc="{{issue.desc}}" data-slug="{{issue.slug}}" data-assigned-to="{{issue.assigned_to.email}}">
                <i class="fas fa-user-plus"></i>
            </a>
            </div>
            {% endif %}
        </div>
        <a class="btn btn-primary btn-sm" href="{% url 'projects:issue_detail' issue.project.slug issue.slug %}">View</a>
    </div>
</div>