accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'

urlpatterns = [
    path('edit-account/', views.ChangeUserDetailsView.as_view(), name='edit_account'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
]

base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from bugtail.helpers import image_helper
from django.conf import settings
# Create your models here.


class User(AbstractUser):
    email = models.EmailField(unique=True)
    pass

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='Something amazing about me')
    profile_pic = models.ImageField(upload_to=image_helper.get_upload_path, null=True, blank=True)
    # image here

    def __str__(self):
        return f'{self.user.email} Profile'
    
    def image_url(self):
        if self.profile_pic:
            return getattr(self.profile_pic, 'url', None)
        else:
            return f'{settings.STATIC_URL}img/avatars/avatar-2.jpg'

accounts/forms.py
from django import forms
from accounts import models


class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'readonly':True}))
    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['bio']
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'bio':
                field.widget.attrs['class'] = 'form-control'
                field.widget.attrs['rows'] = '3'
            else:
                field.widget.attrs['class'] = 'form-control'

accounts/views.py
from allauth.account.forms import ChangePasswordForm
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic.base import View
from bugtail.helpers import form_helper
from accounts import forms
# Create your views here.

class SettingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'add_email_form':form_helper._AddEmailForm(),
            'change_password_form':form_helper._ChangePasswordForm(),
            'profile_form':forms.ProfileForm(instance=self.request.user.profile),
            'user_form': forms.UserForm(instance=self.request.user),
        }
        return render(request, 'settings.html', context)
    

class ChangeUserDetailsView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user_form = forms.UserForm(request.POST,instance=self.request.user)
        profile_form = forms.ProfileForm(request.POST,instance=self.request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Account Updated Successfully 😜')
        else:
            messages.success(request, 'Error Occurred')
        return redirect('accounts:settings') 

accounts/templates/settings.html
{% extends 'base.html' %}
{% load static %}
{% block page_header_title %}Settings{% endblock page_header_title %}
{% block page_header_subtitle %}
Your bounce rate increased by 5.25% over the past 30 days.
{% endblock page_header_subtitle %}
{% block page_content %}

<div class="row">
    <div class="col-md-3 col-xl-2">

        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Profile Settings</h5>
            </div>

            <div class="list-group list-group-flush" role="tablist">
                <a class="list-group-item list-group-item-action active" data-bs-toggle="list" href="#account"
                    role="tab">
                    Account
                </a>
                <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#email" role="tab">
                    Email
                </a>
                <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#password" role="tab">
                    Password
                </a>
                <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#" role="tab">
                    Delete account
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-9 col-xl-10">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="account" role="tabpanel">
                <form action="{% url 'accounts:edit_account' %}" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-actions float-end">
                                <a href="#" class="me-1">
                                    <i class="align-middle" data-feather="refresh-cw"></i>
                                </a>
                                <div class="d-inline-block dropdown show">
                                    <a href="#" data-bs-toggle="dropdown" data-bs-display="static">
                                        <i class="align-middle" data-feather="more-vertical"></i>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-end">
                                        <a class="dropdown-item" href="#">Action</a>
                                        <a class="dropdown-item" href="#">Another action</a>
                                        <a class="dropdown-item" href="#">Something else here</a>
                                    </div>
                                </div>
                            </div>
                            <h5 class="card-title mb-0">Public info</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="mb-3">
                                        <label for="inputUsername">Username</label>
                                        {{user_form.username}}
                                        <!-- <input type="text" class="form-control" id="inputUsername" placeholder="Username"> -->
                                    </div>
                                    <div class="mb-3">
                                        <label for="inputUsername">Biography</label>
                                        {{profile_form.bio}}
                                        <!-- <textarea rows="2" class="form-control" id="inputBio"
                                                placeholder="Tell something about yourself"></textarea> -->
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="text-center">
                                        
                                        <img alt="Chris Wood" src="{{user.profile.image_url}}"
                                            class="rounded-circle img-responsive mt-2" width="128" height="128" />
                                        <div class="mt-2">
                                            <span class="btn btn-primary"><i class="fas fa-upload"></i> Upload</span>
                                        </div>
                                        <small>For best results, use an image at least 128px by 128px in .jpg
                                            format</small>
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">Save changes</button>

                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <div class="card-actions float-end">
                                <a href="#" class="me-1">
                                    <i class="align-middle" data-feather="refresh-cw"></i>
                                </a>
                                <div class="d-inline-block dropdown show">
                                    <a href="#" data-bs-toggle="dropdown" data-bs-display="static">
                                        <i class="align-middle" data-feather="more-vertical"></i>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-end">
                                        <a class="dropdown-item" href="#">Action</a>
                                        <a class="dropdown-item" href="#">Another action</a>
                                        <a class="dropdown-item" href="#">Something else here</a>
                                    </div>
                                </div>
                            </div>
                            <h5 class="card-title mb-0">Private info</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="mb-3 col-md-6">
                                    <label for="inputFirstName">First name</label>
                                    {{user_form.first_name}}
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="inputLastName">Last name</label>
                                    {{user_form.last_name}}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="inputEmail4">Email</label>
                                {{user_form.email}}
                            </div>
                            <button type="submit" class="btn btn-primary">Save changes</button>

                        </div>
                    </div>
                </form>


            </div>
            <div class="tab-pane fade" id="email" role="tabpanel">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Email</h5>
                        {% if user.emailaddress_set.all %}
                        <p>The following e-mail addresses are associated with your account:</p>

                        <form action="{% url 'account_email' %}" class="email_list" method="post">
                            {% csrf_token %}
                            <fieldset class="blockLabels">

                                {% for emailaddress in user.emailaddress_set.all %}
                                <div class="card">
                                    <div class="card-body p-2 d-flex justify-content-between">
                                        <div class="">
                                            <input id="email_radio_{{forloop.counter}}" type="radio" name="email" 
                                            {% if emailaddress.primary or user.emailaddress_set.count is 1 %}checked="checked"
                                            {%endif %} value="{{emailaddress.email}}" />
                                            {{emailaddress.email}}
                                        </div>
                                        <div>
                                            {% if emailaddress.verified %}
                                        <span class="badge bg-success">Verified</span>
                                        {% endif %}
                                        {% if emailaddress.primary %}<span class="badge bg-primary">Primary</span>{% endif %}
                                        </div>
                                        
                                    </div>
                                </div>
                                {% endfor %}
                                <div class="buttonHolder">
                                    <button class="btn btn-primary" type="submit" name="action_primary">Make
                                        Primary</button>
                                    <button class="btn btn-outline-primary" type="submit" name="action_send">Re-send
                                        Verification</button>
                                    <button class="btn btn-outline-danger" type="submit" name="action_remove">Remove
                                        </button>
                                </div>

                            </fieldset>
                        </form>

                        {% else %}
                        <p><strong>Warning:</strong> You currently do not have any e-mail address
                            set up. You should really add an e-mail address so you can receive notifications, reset your
                            password, etc.</p>

                        {% endif %}

                        <div class="my-4">
                            <h5>Add E-mail Address</h5>
                            <form method="post" action="{% url 'account_email' %}" class="add_email">
                                {% csrf_token %}
                                {{ add_email_form.as_p }}
                                <button name="action_add" class="btn btn-outline-primary" type="submit">Add E-mail</button>
                            </form>
                        </div>

                        

                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="password" role="tabpanel">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Password</h5>

                        <form action="{% url 'account_change_password' %}" method="POST">
                            {% csrf_token %}
                            {{change_password_form.as_p}}
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}
{% block custom_scripts %}

{% endblock custom_scripts %}