base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),

]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('-/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<str:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<str:slug>/-/issue/', views.CreateIssueView.as_view(), name='create_issue'),
    path('<str:slug>/-/issue/<str:issue_slug>/', views.IssueView.as_view(), name='issue_detail'),
    path('<str:slug>/add-collaborators/', views.AddRemoveCollaboratorView.as_view(), name='add_remove_collaborator'),
    path('-/assign/', views.assign_task, name='assign_task'),
    path('<str:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<str:slug>/edit/', views.ProjectEditView.as_view(), name='project_edit'),
    path('<str:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
]

projects/models.py
from accounts.models import User
from django.db import models
from bugtail.helpers import model_helper

# Create your models here.

class Project(model_helper.AuthorDescNameTimeBasedModel):
    slug = models.SlugField(default=model_helper.gen_slug)
    collaborators = models.ManyToManyField(User, related_name='collaborators', blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.name} {self.slug} project'
    
    def get_author(self):
        return self.author
    
    def get_collaborators(self):
        collaborators = [self.get_author()]
        return collaborators + list(self.collaborators.all())
    


class IssueLabel(model_helper.TimeBasedModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=10)
    short_name = models.CharField(max_length=5)

    class Meta:
        verbose_name = 'Issue Label'
        verbose_name_plural = 'Issue Labels'

    def __str__(self):
        return f'{self.project.name} - {self.name}'





class Issue(model_helper.NameDescTimeBasedModel):
    class IssuePriorityChoices(models.TextChoices):
        low = 'Low', 'Low'
        high = 'High', 'High'
        moderate = 'Moderate', 'Moderate'
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    slug = models.SlugField(default=model_helper.gen_slug)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, 
        blank=True, related_name='issue_assignee')
    priority = models.CharField(max_length=100, choices=IssuePriorityChoices.choices,
    default=IssuePriorityChoices.moderate)
    label = models.ForeignKey(IssueLabel, on_delete=models.SET_NULL, null=True, blank=True,
    related_name='issue_label')


    class Meta:
        verbose_name = 'Issue'
        verbose_name_plural = 'Issues'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.project.slug} task {self.slug} - {self.created_at.date()}' 

    def assginee_image(self):
        return self.assigned_to.profile.image_url()

    

projects/forms.py
from django import forms
from projects.models import Issue, Project
from bugtail.helpers.form_helper import add_form_control


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'desc']
    
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        add_form_control(self)

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        exclude = ['project', 'slug', 'label']

    
    def __init__(self, *args, **kwargs):
        super(IssueForm, self).__init__(*args, **kwargs)
        add_form_control(self)

projects/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    )
from django.contrib import messages
from django.views.generic import (
    ListView,
    CreateView,
    DeleteView,
    UpdateView
)
from django.http import JsonResponse
from django.views.generic.base import View
from accounts.models import User
from bugtail.helpers.project_helper import get_user_projects
from comments.forms import CommentForm
from projects import models
import json
from django.core.serializers import serialize
from projects.forms import IssueForm, ProjectForm
from collaborators.models import CollaborationRequest
# Create your views here.

class ProjectListView(LoginRequiredMixin, ListView):
    context_object_name = 'projects'
    template_name = 'projects/list.html'

    def get_queryset(self):
        return get_user_projects(self.request.user) #models.Project.objects.filter(author=self.request.user)

class ProjectCreateView(LoginRequiredMixin, CreateView):
    form_class = ProjectForm
    template_name = 'projects/new.html'

    def form_valid(self, form):
        project = form.save(commit=False)
        project.author = self.request.user
        project.save()
        return redirect('projects:project_detail', project.slug)

class ProjectDetailView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'projects/detail.html'

    def get_project(self):
        return models.Project.objects.get(slug=self.kwargs['slug'])
    
    def get_labels(self):
        labels = models.IssueLabel.objects.filter(project=self.get_project())
        return labels


    def get(self, request, *args, **kwargs):
        labels = self.get_labels()
        if request.is_ajax():
            data = {}
            data['labels'] = serialize('json', queryset=labels)
            return JsonResponse(data)

        context = {
            'project':self.get_project(),
            'labels' : labels,
            'form': IssueForm(),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            ajaxData = request.POST
            label = models.IssueLabel.objects.get(project__slug=self.kwargs['slug'],
                short_name=ajaxData['to'])
            print(label)
            issue = models.Issue.objects.get(slug=ajaxData['slug'])
            issue.label = label
            issue.save()
            data = {}
            data['message'] = 'Successful'
            return JsonResponse(data)
    
    def test_func(self):
        if self.get_project().author == self.request.user:
            return True
        return False
    
    def handle_no_permission(self):
        messages.success(self.request, 'You have no permission to view this page')
        return redirect('base:dashboard')

class ProjectSettingsView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'projects/settings.html'

    def get_project(self):
        return models.Project.objects.get(slug=self.kwargs['slug'])

    def get(self, request, *args, **kwargs):
        project = self.get_project()
        projectForm = ProjectForm(instance=project)
        context = {
            'project':project,
            'projectForm':projectForm
        }
        return render(request, self.template_name, context)

    def test_func(self):
        if self.get_project().author == self.request.user:
            return True
        return False
    
    def handle_no_permission(self):
        messages.success(self.request, 'You have no permission to view this page')
        return redirect('base:dashboard')


class ProjectEditView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'projects/new.html'

    def get_project(self):
        return models.Project.objects.get(slug=self.kwargs['slug'])

    def post(self, request, *args, **kwargs):
        form = ProjectForm(request.POST, instance=self.get_project())
        if form.is_valid:
            form.save()
            messages.success(self.request, 'Project Updated successfully')
            return redirect('projects:project_detail', self.get_project().slug)

    def test_func(self):
        if self.get_project().author == self.request.user:
            return True
        return False
    
    def handle_no_permission(self):
        messages.success(self.request, 'You have no permission to view this page')
        return redirect('base:dashboard')

class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'projects/detail.html'

    def get_project(self):
        return models.Project.objects.get(slug=self.kwargs['slug'])

    def get(self, request, *args, **kwargs):
        try:
            project = self.get_project()
            project.delete()
            messages.success(self.request, 'Project deleted successfully')
        except models.Project.DoesNotExist:
            messages.success(self.request, 'This project seems to not exist')
        return redirect('projects:project_list')

    def test_func(self):
        if self.get_project().author == self.request.user:
            return True
        return False
    
    def handle_no_permission(self):
        messages.success(self.request, 'You have no permission to view this page')
        return redirect('base:dashboard')


def assign_task(request):
    if request.is_ajax():
        user = None
        if request.GET.get('email') != '':
            email = request.GET.get('email')
            user = User.objects.get(email=email)
        slug = request.GET.get('task')
        task = models.Issue.objects.get(slug=slug)
        
        task.assigned_to = user if user else None
        task.save()
        data = {}
        data['message'] = f'Task Assigned 🎈 to {user}' if user else f'Task Unassigned'
        data['messageType'] = 'success'
        return JsonResponse(data)
    return redirect('project:project_list')

class AddRemoveCollaboratorView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            ajaxData = request.GET
            data = {}
            project = models.Project.objects.get(slug=self.kwargs['slug'])
            user = User.objects.get(email=ajaxData['email'])
            project.collaborators.remove(user)
            data['message'] = f'Collaborator with email {ajaxData["email"]} has been removed'
            data['messageType'] = 'success'
            return JsonResponse(data, safe=False)
    def post(self, request, *args, **kwargs):
        
        if request.is_ajax():
            data = {}
            ajaxData = request.POST
            project = models.Project.objects.get(slug=self.kwargs['slug'])
            #Check if user exists
            try:
                user = User.objects.get(email=ajaxData['email'])
                if project.collaborators.filter(email=user.email).exists():
                    data['message'] = 'User with email '+ ajaxData['email'] +' is already a collaborator on '+ project.name
                    data['messageType'] = 'info'
                else:
                    project.collaborators.add(user)
                    data['message'] = 'Collaborator with email:'+ ajaxData['email']+' has been added'
                    data['messageType'] = 'success'
            except:
                data['message'] = 'User with email '+ ajaxData['email'] +' Appears not to Exist, Please Check Email and try Again'
                data['messageType'] = 'error'
            return JsonResponse(data, safe=False)


class CreateIssueView(LoginRequiredMixin,UserPassesTestMixin,View):
    def get_project(self):
        return models.Project.objects.get(slug=self.kwargs['slug'])
    
    def post(self, request, *args, **kwargs):
        label = models.IssueLabel.objects.get(project=self.get_project(), short_name='open')
        ajaxData = request.POST
        data = {}
        if ajaxData['label']:
            label = models.IssueLabel.objects.get(project=self.get_project(), short_name=ajaxData['label'])
        issue = {
            'project':self.get_project(),
            'name' : ajaxData['title'],
            'desc' : ajaxData['desc'],
            'priority': ajaxData['priority'],
            'label': label

        }
        models.Issue.objects.create(**issue)
        data['message'] = 'Issue Created Successfully'
        data['messageType'] = 'success'
        return JsonResponse(data, safe=False)
        

    def test_func(self):
        user = self.request.user
        if  user == self.get_project().author or user in self.get_project().collaborators.all():
            return True
        return False
    
    def handle_no_permission(self):
        messages.success(self.request, 'You can\'t add issues in this project')
        return redirect('base:dashboard')


class IssueView(LoginRequiredMixin,UserPassesTestMixin, View):
    template_name = 'issues/detail.html'

    def get_project(self):
        return models.Project.objects.get(slug=self.kwargs['slug'])
    
    def get_issue(self):
        return models.Issue.objects.get(project__slug=self.get_project().slug, slug=self.kwargs['issue_slug'])
    
    def get(self, request, *args, **kwargs):
        commentForm = CommentForm()
        context = {
            'issue':self.get_issue(),
            'commentForm' : commentForm,
        }
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwrgs):
        commentForm = CommentForm(request.POST)
        comment = commentForm.save(commit=False)
        comment.author, comment.issue = self.request.user, self.get_issue()
        comment.save()
        messages.success(request, 'Comment Uploaded successfully')
        return redirect('projects:issue_detail', self.get_issue().project.slug,self.get_issue().slug)
        # if request.is_ajax():
        #     data = {}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load project_extras %}
{% block page_header_title %}{{project.name}}{% endblock page_header_title %}
{% block page_header_subtitle %}
    {{project.desc}}.
{% endblock page_header_subtitle %}
{% block contributor %}
<a class="text-white btn btn-primary" title="Add a Collaborator"
data-bs-toggle="modal" data-bs-target="#addCollaboratorModal">
    <i class="fas fa-user-plus"></i>
</a>
{% include 'partials/_add_collaborator_modal.html' %}
<a class="text-white btn btn-outline-primary" title="Collaborators" 
data-bs-toggle="modal" data-bs-target="#collaboratorsModal">
    <i class="fas fa-user-friends"></i>
</a>
{% include 'partials/_collaborators_modal.html' with collaborators=project.collaborators.all %}                                
{% endblock contributor %}
{% block page_content %}
<div style="overflow: scroll;max-height: 500px;">
    <div class="d-flex gx-5">
        {% for label in labels %}
        <div class="col-12 col-lg-6 col-xl-4">
            <div class="p-3">
                <div class="card">
                    <div class="card-header">
                        <div class="card-actions float-end">
                            <a href="#" class="me-1 btn btn-light" type="button" 
                                data-bs-toggle="modal" data-bs-target="#centeredIssueModal">
                                <i class="align-middle" data-feather="plus"></i>
                            </a>
                        </div>
                        <h5 class="card-title">{{label.name.title}}</h5>
                    </div>
                    <div class="card-body p-3">
                        <div id="tasks-{{label.short_name}}">
                                <div class="card mb-3 bg-light cursor-grab" style="height: 5px;opacity: 0;">
                                    
                                </div>
                                {% fetch_label_tasks project.slug label.short_name as issues %}
                                {% for issue in issues %}
                                {% include 'partials/_task_card.html' %}
                                {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% include 'partials/_issue_modal.html' with form=form project=project %}
{% include 'partials/_right_offset_canva.html' with project=project %}
{% endblock page_content %}
{% block custom_scripts %}
<script>
document.addEventListener("DOMContentLoaded", function() {
    
    $.ajax({
        url : `{% url 'projects:project_detail' 1500 %}`.replace(1500, '{{project.slug}}'),
        method : 'GET',
        success: res => {
            const { labels } = res
            let labell = JSON.parse(labels)
            let label_list = [...labell].map(label => document.querySelector('#tasks-'+label.fields.short_name))
            dragula(label_list, {
                copy: false,
                moves: function (el, source, handle, sibling) {
                    return true; 
                },
                accepts: function (el, target, source, sibling) {
                    const taskTo = target.id.split('-')[1]
                    const { slug } = el.dataset
                    $.ajax({
                        url : `{% url 'projects:project_detail' 1500 %}`.replace(1500, '{{project.slug}}'),
                        method : 'POST',
                        headers: {
                            "X-CSRFToken": '{{ csrf_token }}'
                        },
                        data : {to : `${taskTo}`, slug: slug},
                        success : res => {
                            `Working Here`
                        },
                        error : err => {
                            err;
                        }
                        
                    })
                    return true; 
                },
            })
        },
        error : err => {
            showNotification('Error Loading Page', 'error')
        }
    })

    
});
const getTask = e => {
        const {title, desc, slug} = e.dataset
        document.querySelector('#offcanvas-desc').textContent = desc
        document.querySelector('#assign-select').setAttribute('data-slug', slug)
    }

const assignTask = e =>{

    const data = {
        email : e.value,
        task: e.dataset.slug
    }
    $.ajax({
        url : `{% url 'projects:assign_task' %}`,
        method : 'GET',
        data : data,
        success : res => {
            showNotification(res['message'], res['messageType'])
        },
        error : err => {
            showNotification('Error Trying to assign task', 'error')
        }
    })
}

const addCollaborator = () => {
    let collaboratorEmail = document.querySelector('#addCollaboratorField').value
    $.ajax({
        url : `{% url 'projects:add_remove_collaborator' 1500 %}`.replace(1500, '{{project.slug}}'),
        method : 'POST',
        headers : {'X-CSRFToken':'{{csrf_token}}'},
        data : {email : collaboratorEmail},
        success : res => {
            showNotification(res['message'], res['messageType'])
            document.querySelector('#addCollaboratorField').value = ''
            $('#addCollaboratorModal').modal('hide')
        },
        error : err => {
            showNotification('Error Trying to send mail to Collaborator', 'error')
        }
    })
}

const removeCollaborator = (e) => {
    const  {email} = e.dataset
    $.ajax({
        url : `{% url 'projects:add_remove_collaborator' 1500 %}`.replace(1500, '{{project.slug}}'),
        method : 'GET',
        // headers : {'X-CSRFToken':'{{csrf_token}}'},
        data : {email : email},
        success : res => {
            showNotification(res['message'], res['messageType'])
            $('#collaboratorsModal').modal('hide')
            document.getElementById(`user-${email}`).style.display='none'
            
        },
        error : err => {
            showNotification('Error Trying to send mail to Collaborator', 'error')
        }
    })
}

document.querySelector('.issueForm').addEventListener('submit', e => {
    e.preventDefault();
    const title = $('#issueTitle').val()
    const desc = $('#issueDesc').val()
    const priority = $('#id_priority').val()
    const label = $('#issueLabel').val()
    $('#issueTitle').val(''), $('#issueDesc').val('')
    $.ajax({
        url : `{% url 'projects:create_issue' 1500 %}`.replace(1500, '{{project.slug}}'),
        method : 'POST',
        headers : {'X-CSRFToken':'{{csrf_token}}'},
        data : {'title':title, 'desc':desc, 'priority':priority, 'label':label},
        success : res => {
            $('#centeredIssueModal').modal('hide')
            showNotification(res['message'], res['messageType'])
            setTimeout(() => {
                location.reload();

            }, 2000)
        },
        error : err => {
            showNotification('Error Trying to Create Issue', 'error')
        },
    })
    $('#issueTitle').val(''), $('#issueDesc').val('')
})
</script>
{% endblock custom_scripts %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block page_header_title %}
	Projects
	{% endblock page_header_title %}
	{% block page_header_subtitle %}
		Listing displays both your projects and the ones that involves you.
	{% endblock page_header_subtitle %}
{% block contributor %}
<a href="{% url 'projects:project_create' %}" class="text-white btn btn-primary" title="Create a Project">
    <i class="fas fa-project-diagram"></i>
</a>                               
{% endblock contributor %}
{% block page_content %}
<div class="row">
	{% if projects %}
    {% for project in projects %}
	<div class="col-12 col-md-12 col-xxl-12">
		<div class="card flex-fill w-100">
			<div class="card-header">
				<div class="card-actions float-end">
					<a href="#" class="me-1">
						<i class="align-middle" data-feather="refresh-cw"></i>
					</a>
					<div class="d-inline-block dropdown show">
						<a href="#" data-bs-toggle="dropdown" data-bs-display="static">
							<i class="align-middle" data-feather="more-vertical"></i>
						</a>

						<div class="dropdown-menu dropdown-menu-end">
							<a class="dropdown-item" href="{% url 'projects:project_detail' project.slug %}">View</a>
							{% if project.author == request.user %}
							<a class="dropdown-item" href="{% url 'projects:project_settings' project.slug %}">Settings</a>
							{% endif %}
						</div>
					</div>
				</div>
				<h5 class="card-title my-0">{{project.name}}</h5>
				<p class="card-text">{{project.desc | linebreaks}}</p>
			</div>
		</div>
	</div>
    {% endfor %}
	{% else %}
	<div class="col-12">
		<div class="card p-3">
			<p>You have not Project Yet! <span class="fw-bold">Start a Project <a href="{% url 'projects:project_create' %}">Here</a></span></p>
		</div>
	</div>
	{% endif %}
</div>

{% endblock page_content %}
{% block custom_scripts %}
<script>

</script>
{% endblock custom_scripts %}

projects/templates/projects/new.html
{% extends 'base.html' %}
{% block page_content %}
	{% block page_header_title %}
	New Project
	{% endblock page_header_title %}
	{% block page_header_subtitle %}
		
	{% endblock page_header_subtitle %}
	{% block side_widgets %}
    <!-- <a class="btn btn-light" href="{% url 'projects:project_create' %}">New Project</a> -->
    {% endblock side_widgets %}
<div class="row">
    <div class="col-12 col-md-12 col-xxl-12">
		<div class="card flex-fill w-100">
			<div class="card-header">
				
				<!-- <h5 class="card-title my-0">Project Info</h5> -->
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
				<!-- <p class="card-text">{{project.desc | linebreaks}}</p> -->
				
			</div>
		</div>
	</div>
</div>

{% endblock page_content %}
{% block custom_scripts %}
<script>

</script>
{% endblock custom_scripts %}

projects/templates/projects/settings.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
{% block page_header_title %}{{project.name.title}} Settings{% endblock page_header_title %}
{% block page_header_subtitle %}
{{project.desc | truncatewords:10}}
{% endblock page_header_subtitle %}
<div class="row">
    <div class="col-md-3 col-xl-2">

        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Project Settings</h5>
            </div>

            <div class="list-group list-group-flush" role="tablist">
                <a class="list-group-item list-group-item-action active" data-bs-toggle="list" href="#editproject"
                    role="tab">
                    Edit
                </a>
                <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#email" role="tab">
                    Change Ownership
                </a>
                <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#password" role="tab">
                    Delete
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-9 col-xl-10">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="editproject" role="tabpanel">
                <form action="{% url 'projects:project_edit' project.slug %}" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title mb-0">Edit Project Info</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    {{projectForm.as_p}}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Save changes</button>

                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="email" role="tabpanel">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Email</h5>
                        {% if user.emailaddress_set.all %}
                        <p>The following e-mail addresses are associated with your account:</p>

                        <form action="{% url 'account_email' %}" class="email_list" method="post">
                            {% csrf_token %}
                            <fieldset class="blockLabels">

                                {% for emailaddress in user.emailaddress_set.all %}
                                <div class="card">
                                    <div class="card-body p-2 d-flex justify-content-between">
                                        <div class="">
                                            <input id="email_radio_{{forloop.counter}}" type="radio" name="email" 
                                            {% if emailaddress.primary or user.emailaddress_set.count is 1 %}checked="checked"
                                            {%endif %} value="{{emailaddress.email}}" />
                                            {{emailaddress.email}}
                                        </div>
                                        <div>
                                            {% if emailaddress.verified %}
                                        <span class="badge bg-success">Verified</span>
                                        {% endif %}
                                        {% if emailaddress.primary %}<span class="badge bg-primary">Primary</span>{% endif %}
                                        </div>
                                        
                                    </div>
                                </div>
                                {% endfor %}
                                <div class="buttonHolder">
                                    <button class="btn btn-primary" type="submit" name="action_primary">Make
                                        Primary</button>
                                    <button class="btn btn-outline-primary" type="submit" name="action_send">Re-send
                                        Verification</button>
                                    <button class="btn btn-outline-danger" type="submit" name="action_remove">Remove
                                        </button>
                                </div>

                            </fieldset>
                        </form>

                        {% else %}
                        <p><strong>Warning:</strong> You currently do not have any e-mail address
                            set up. You should really add an e-mail address so you can receive notifications, reset your
                            password, etc.</p>

                        {% endif %}

                        <div class="my-4">
                            <h5>Add E-mail Address</h5>
                            <form method="post" action="{% url 'account_email' %}" class="add_email">
                                {% csrf_token %}
                                {{ add_email_form.as_p }}
                                <button name="action_add" class="btn btn-outline-primary" type="submit">Add E-mail</button>
                            </form>
                        </div>

                        

                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="password" role="tabpanel">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Delete Project</h5>
                        <div class="my-3">
                            <div>
                                <p>
                                    This action cannot be undone. This will permanently delete the {{project.author.username}}/{{project.name}} project, wiki, issues, comments, packages, secrets, workflow runs, and remove all collaborator associations.
                                </p>
                                <p>
                                    Please type 
                                    <span class="fw-bolder" id="project-key">{{project.author.username}}/{{project.name}}</span> to confirm</p>
                            </div>
                            <input type="text" class="form-control" onkeyup="getValue(this)">
                            <div class="my-3">
                                <a href="{% url 'projects:project_delete' project.slug %}" id="btnDelete" class="btn btn-danger disabled">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}
{% block custom_scripts %}
<script>
    const getValue  = e =>{
        const inputValue = document.querySelector('#project-input')
        let value = document.querySelector('#project-key').textContent
        e.value == value ? $('#btnDelete').removeClass('disabled'):$('#btnDelete').addClass('disabled')
    } 
</script>
{% endblock custom_scripts %}